### ISSUE TITLE
set flag to Norway fails to show a flag 

### ISSUE THREAD

**Issue by killajoe** [Ebsy/discourse-nationalflags#5]
.. it set flag to 
**plugins/discourse-nationalflags/images/nationalflags/false.png**
but should set it to 
**plugins/discourse-nationalflags/images/nationalflags/no.png**
the reason is that the link is missing here?
https://github.com/Ebsy/discourse-nationalflags/blob/master/config/locales/client.en.yml

**no: Norway**

**Comment by killajoe** [comment]
merged thanks!

**Comment by killajoe** [comment]
We do not watch this issue some times.. but we see that also we have latest version of the plugin installed, norway flag still is not working at our discourse here:
https://forum.endeavouros.com/t/bug-inside-forum-discourse-norway-flag-missing/2851/10
![alt text](https://i.imgur.com/rAJe4ar.png "latest revision")
![alt text](https://i.imgur.com/TJc1bpQ.png "latest version")

**Comment by mentalstring** [comment]
I confirm, still not fixed on the latest version. This was on a fresh installation with the latest stable Discourse.

**Comment by Ebsy** [comment]
@merefield What do you reckon to this? it seems that 'no' is somehow being translated as false? It's a weird one.
I can change the references from 'no' to 'nor' but then that'd be the only exception to the rest of the ISO codes. What do you think?

**Comment by mentalstring** [comment]
@Ebsy: 'no' is [reserved keyword](https://makandracards.com/makandra/24809-yaml-keys-like-yes-or-no-evaluate-to-true-and-false) in YAML. Also, there is this https://github.com/Ebsy/discourse-nationalflags/blob/a0fbdb0889911837476596174d551c0124493d00/config/locales/client.en.yml#L77

I submitted a [PR](https://github.com/Ebsy/discourse-nationalflags/pull/11) yesterday that fixes this and seems to be working for me.

**Comment by Ebsy** [comment]
@mentalstring 
not very happy with the 'false' workaround. hmmm

your PR looks really good! I had no idea about the reserved keyword. Thanks a lot for that.
